services:  
  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV : PROD
    links:
      - dnmonster
      - redis
    networks:
      - bridge

  dnmonster:
    image : amouat/dnmonster:1.0
  
  redis:
    image : redis:latest


networks:
  bridge:
    external : true 
